import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { DarkTheme } from "@react-navigation/native";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jyoti's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="dark">
      {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
